name: Localize CI

on:
  push:
    branches:
      - main
      - 'stable/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: pre-commit/action@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test-sqlite:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9']
        django: ['2.2']
        wagtail: ['2.11', '2.12', '2.13']
        include:
          # Add test for Django 3.2 that is only suported on Wagtail 2.13+
          - python: '3.9'
            django: '3.2'
            wagtail: '2.15'
          - python: '3.9'
            django: '3.2'
            wagtail: '2.16'
          - python: '3.9'
            django: '3.2'
            wagtail: '3.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ hashFiles('setup.py') }}-py${{ matrix.python }}-dj${{ matrix.django }}-w${{ matrix.wagtail }}-sqlite
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite

  test-postgres:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    needs: lint
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9']
        django: ['2.2']
        wagtail: ['2.11', '2.12', '2.13']
        postgres: ['10.8']
        experimental: [false]
        include:
          # Add test for Django 3.2 that is only suported on Wagtail 2.13+
          - python: '3.9'
            django: '3.2'
            wagtail: '2.14'
            postgres: '10.8'
            experimental: false
          - python: '3.9'
            django: '3.2'
            wagtail: '2.15'
            postgres: '10.8'
            experimental: false
          - python: '3.9'
            django: '3.2'
            wagtail: '2.16'
            postgres: '10.8'
            experimental: false
          - python: '3.9'
            django: '4.0'
            wagtail: '2.16'
            postgres: '10.8'
            experimental: false
          - python: '3.9'
            django: '3.2'
            wagtail: '3.0'
            postgres: '10.8'
            experimental: false
          - python: '3.9'
            django: '4.0'
            wagtail: '3.0'
            postgres: '10.8'
            experimental: false
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ hashFiles('setup.py') }}-py${{ matrix.python }}-dj${{ matrix.django }}-w${{ matrix.wagtail }}-postgres
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_localize
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-postgres

  coverage:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.8']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install django~=3.2
          pip install -e.[testing]
          pip install coverage==5.4
      - name: Test
        run: |
          coverage run testmanage.py test
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
